const NAVIGATION_NAME = {
  LoginScreen: 'LoginScreen',
  LoginCompanyScreen: 'LoginCompanyScreen',
  MainAccount: 'MainAccount',
  ChangeStore: 'ChangeStore',
  ChangePassword: 'ChangePassword',
  HomeScreen: 'HomeScreen',
  SearchProductScreen: 'SearchProductScreen',
  ListPriceChange: 'ListPriceChange',
  ListPricePolicy: 'ListPricePolicy',
  DetailPricePolicy: 'DetailPricePolicy',
  CancelOrderStatistic: 'CancelOrderStatistic',
  CashierLoginHistory: 'CashierLoginHistory',
  ConfirmOrder: 'ConfirmOrder',
  SelectProduct: 'SelectProduct',
  SelectSupplier: 'SelectSupplier',
  ListPO: 'ListPO',
  DetailPO: 'DetailPO',
  EditPO: 'EditPO',
  ListInventoryPeriod: 'ListInventoryPeriod',
  DetailInventoryPeriod: 'DetailInventoryPeriod',
  ListLocation: 'ListLocation',
  ContactScreen: 'ContactScreen',
  ShareScreen: 'ShareScreen',
  ImportItem: 'ImportItem',
  ListTally: 'ListTally',
};

export default NAVIGATION_NAME;
