export default {
  API: {
    GetDomain: 'https://api.olbius.com/token',
    // baseURL: 'https://demold.olbius.com/mobileservices/control',
    baseURL: 'https://testldmarket.olbius.com/mobileservices/control',
    baseImgURL: 'https://demold.olbius.com',
    urlGetDomain: 'https://api.olbius.com/token',
    Login: '/mobilelogin',
    Logout: '/logout',
    GetCustomer: '/mGetCustomers',
    GetListProduct: '/getPriceTax',
    GetCustomerRegistration: '/mGetCustomerRegistration',
    GetSaleOrder: '/mGetSalesOrders',
    GetOrderDetail: '/mGetSalesOrderDetails',
    GetProductDetail: '/mGetProductInfoDetail',
    GetListPriceChange: '/mGetListPriceChange',
    GetOrderPromotions: '/getOrderPromotions',
    GetDetailPromotion: '/getOrderPromotion',
    GetListPromotionExt: '/mGetListPromotionExt',
    GetPromotionExtInfoDetail: '/mGetPromotionExtInfoDetail',
    GetCustomerReport: '/mGetCustomerReports',
    GetSalesmanReport: '/mGetTurnoverBySalesmanReports',
    CreateCustomerAgent: '/createCustomerAgent',
    ChangePassWord: '/mUpdatePassWordMobilemcs',
    CreateCart: '/createCart',
    ModifyCart: '/modifyCart',
    SubmitOrder: '/submitOrder',
    GetProductStore: '/getProductStore',
    EmptyCart: '/emptycart',
    CreateRegistrationPromotion: '/mcreateRegistrationPromotion',
    SalesmanCheckIn: '/salesmanCheckIn',
    SalesmanCheckOut: '/salesmanCheckOut',
    GetInventoryCusInfo: '/getInventoryCusInfo',
    UpdateInventoryCus: '/updateInventoryCus',
    GetListProductExpRecent: '/mGetListProductExpRecent',
    UpdateQtyProductExpInvent: '/mUpdateQtyProductExpInvent',
    GetAllRoute: '/getAllRoute',
  },
  RESPONSE_CODES: {
    SUCCESS: {
      SUCCESS: 200,
    },
    ERROR: {
      INTERNAL_SERVER: 500,
      NOT_FOUND: 404,
    },
  },
  GOOGLE_MAP_API: 'AIzaSyCHu4vQUKFsMnqpjk_HHjIIAU_yejvT5cs',
};
